### ISSUE TITLE
Psr-4 autoloading Table

### ISSUE THREAD

**Issue by hienpro1302** [fxcjahid/Laravel-table-of-content#1]
<img width="976" alt="image" src="https://user-images.githubusercontent.com/94742611/226881092-d9088fc0-ad1e-42f7-ad2d-31ca2bcddc4e.png">

**Comment by fxcjahid** [comment]
Thanks @hienpro1302 
Fixed on version 2.1

**Comment by yassinetrbls** [comment]
Hey, i've still got the same issue
